apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello-hom
resources:
- ../../base/hello-deployment.yaml
- hello-hom-ns.yaml
patchesJson6902:
  - target:
      version: v1
      group: apps
      kind: Deployment
      name: hello-ccee
      namespace: hello-hom
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: hom